const q=(id,prompt,options,correct,explanation,art=null,category='Yleistieto',family=id)=>({id,prompt,options,correct,explanation,art,category,family});
export const extraGeneral=[],extraWorld=[],extraOrder=[],extraImages=[];
const facts=(prefix,category,prompt,rows)=>rows.forEach(([subject,correct,...wrong],i)=>extraGeneral.push(q(`${prefix}${i}`,prompt.replace('{x}',subject),[correct,...wrong],0,`${subject}: ${correct}.`,null,category)));
facts('lit','Kirjat','Kuka kirjoitti teoksen {x}?',[
 ['Tuntematon sotilas','Väinö Linna','Aleksis Kivi','Mika Waltari','Eino Leino'],['Sinuhe egyptiläinen','Mika Waltari','Väinö Linna','Juhani Aho','Arto Paasilinna'],['Rautatie','Juhani Aho','Aleksis Kivi','Eino Leino','Veijo Meri'],['Jäniksen vuosi','Arto Paasilinna','Mika Waltari','Väinö Linna','Juhani Aho'],['Taru sormusten herrasta','J. R. R. Tolkien','J. K. Rowling','C. S. Lewis','George Orwell'],['Harry Potter ja viisasten kivi','J. K. Rowling','J. R. R. Tolkien','Agatha Christie','Astrid Lindgren'],['Peppi Pitkätossu','Astrid Lindgren','Tove Jansson','Selma Lagerlöf','Enid Blyton'],['Romeo ja Julia','William Shakespeare','Charles Dickens','Jane Austen','Oscar Wilde'],['Ylpeys ja ennakkoluulo','Jane Austen','Emily Brontë','Virginia Woolf','Agatha Christie'],['Eläinten vallankumous','George Orwell','Aldous Huxley','Ray Bradbury','Ernest Hemingway'],['Don Quijote','Miguel de Cervantes','William Shakespeare','Jules Verne','Victor Hugo'],['Pieni prinssi','Antoine de Saint-Exupéry','Jules Verne','Victor Hugo','Albert Camus'],['Liisa Ihmemaassa','Lewis Carroll','J. M. Barrie','Roald Dahl','Charles Dickens'],['Matilda','Roald Dahl','Astrid Lindgren','Tove Jansson','Lewis Carroll'],['Muumipeikko ja pyrstötähti','Tove Jansson','Astrid Lindgren','Arto Paasilinna','Selma Lagerlöf'],['Frankenstein','Mary Shelley','Bram Stoker','Edgar Allan Poe','Oscar Wilde'],['Dracula','Bram Stoker','Mary Shelley','Stephen King','H. G. Wells'],['Kaksikymmentätuhatta peninkulmaa meren alla','Jules Verne','H. G. Wells','Jack London','Herman Melville'],['Vanha mies ja meri','Ernest Hemingway','John Steinbeck','George Orwell','Mark Twain'],['Rikos ja rangaistus','Fjodor Dostojevski','Leo Tolstoi','Anton Tšehov','Nikolai Gogol']
]);
facts('chem','Luonnontiede','Mitä alkuaineen merkki {x} tarkoittaa?',[
 ['Fe','Rautaa','Fluoria','Fosforia','Franciumia'],['Ag','Hopeaa','Kultaa','Argonia','Alumiinia'],['Cu','Kuparia','Kalsiumia','Kromia','Hiiltä'],['Na','Natriumia','Typpeä','Neonia','Nikkeliä'],['K','Kaliumia','Kalsiumia','Kuparia','Kobolttia'],['O','Happea','Kultaa','Osmiumia','Vetyä'],['H','Vetyä','Heliumia','Happea','Elohopeaa'],['He','Heliumia','Vetyä','Happea','Hafniumia'],['C','Hiiltä','Kalsiumia','Klooria','Kromia'],['N','Typpeä','Natriumia','Neonia','Nikkeliä'],['Ca','Kalsiumia','Hiiltä','Kuparia','Kadmiumia'],['Cl','Klooria','Kalsiumia','Kobolttia','Hiiltä'],['Pb','Lyijyä','Platina','Fosforia','Palladiumia'],['Sn','Tinaa','Rikkiä','Piitä','Seleeniä'],['Si','Piitä','Hopeaa','Rikkiä','Strontiumia'],['Zn','Sinkkiä','Zirkoniumia','Typpeä','Kultaa'],['Mg','Magnesiumia','Mangaania','Elohopeaa','Molybdeeniä'],['Hg','Elohopeaa','Vetyä','Happea','Hopeaa'],['S','Rikkiä','Piitä','Seleeniä','Natriumia'],['P','Fosforia','Platina','Lyijyä','Kaliumia']
]);
facts('music','Musiikki','Keneen teos {x} liittyy säveltäjänä?',[
 ['Finlandia','Jean Sibelius','Leevi Madetoja','Oskar Merikanto','Toivo Kuula'],['Neljä vuodenaikaa','Antonio Vivaldi','Johann Sebastian Bach','Ludwig van Beethoven','Frédéric Chopin'],['Taikahuilu','Wolfgang Amadeus Mozart','Richard Wagner','Giuseppe Verdi','Giacomo Puccini'],['Joutsenlampi','Pjotr Tšaikovski','Igor Stravinski','Sergei Prokofjev','Dmitri Šostakovitš'],['Carmen','Georges Bizet','Giuseppe Verdi','Giacomo Puccini','Maurice Ravel'],['Boléro','Maurice Ravel','Claude Debussy','Camille Saint-Saëns','Georges Bizet'],['Peer Gynt','Edvard Grieg','Jean Sibelius','Carl Nielsen','Gustav Mahler'],['Nibelungin sormus','Richard Wagner','Giuseppe Verdi','Georges Bizet','Johannes Brahms'],['Pähkinänsärkijä','Pjotr Tšaikovski','Antonio Vivaldi','Sergei Rahmaninov','Franz Schubert'],['Kuutamosonaatti','Ludwig van Beethoven','Johann Sebastian Bach','Wolfgang Amadeus Mozart','Franz Liszt']
]);
facts('fiction','Viihde','Missä tarinassa tai maailmassa esiintyy {x}?',[
 ['Darth Vader','Star Wars','Star Trek','Harry Potter','Taru sormusten herrasta'],['Hogwarts eli Tylypahka','Harry Potter','Narnia','Star Wars','Pokémon'],['Frodo Reppuli','Taru sormusten herrasta','Harry Potter','Narnia','Muumit'],['Pikachu','Pokémon','Super Mario','Sonic','Minecraft'],['Luigi','Super Mario','Sonic','Zelda','Pokémon'],['Sonic-siili','Sonic','Super Mario','Pokémon','Animal Crossing'],['Aku Ankka','Disney','Muumit','Pokémon','Narnia'],['Nuuskamuikkunen','Muumit','Peppi Pitkätossu','Narnia','Harry Potter'],['Sherlock Holmes','Arthur Conan Doylen salapoliisitarinat','Agatha Christien Poirot-tarinat','Harry Potter','Narnia'],['Hercule Poirot','Agatha Christien salapoliisitarinat','Sherlock Holmes','Narnia','Muumit'],['Gollum','Taru sormusten herrasta','Harry Potter','Star Wars','Pokémon'],['Voldemort','Harry Potter','Narnia','Star Wars','Taru sormusten herrasta'],['Spock','Star Trek','Star Wars','Harry Potter','Doctor Who'],['Aslan','Narnia','Harry Potter','Taru sormusten herrasta','Muumit'],['Haisuli','Muumit','Narnia','Peppi Pitkätossu','Pokémon'],['Link','The Legend of Zelda','Super Mario','Sonic','Minecraft'],['Lara Croft','Tomb Raider','The Legend of Zelda','Pokémon','Super Mario'],['Steve, kuutiomainen pelihahmo','Minecraft','Super Mario','Pokémon','Sonic'],['Sauron','Taru sormusten herrasta','Harry Potter','Star Wars','Narnia'],['Totoron metsähenki','Naapurini Totoro','Leijonakuningas','Frozen','Muumit']
]);
facts('words','Kieli','Mitä englannin sana {x} tarkoittaa?',[
 ['apple','Omena','Päärynä','Persikka','Luumu'],['forest','Metsä','Joki','Saari','Vuori'],['bridge','Silta','Portti','Polku','Aita'],['cloud','Pilvi','Sade','Tuuli','Lumi'],['library','Kirjasto','Kirjakauppa','Koulu','Laboratorio'],['butterfly','Perhonen','Leppäkerttu','Sudenkorento','Mehiläinen'],['harbour','Satama','Lentokenttä','Asema','Silta'],['mirror','Peili','Ikkuna','Lamppu','Kehys'],['ladder','Tikkaat','Ovi','Aita','Silta'],['copper','Kupari','Hopea','Tina','Lyijy'],['cucumber','Kurkku','Kesäkurpitsa','Porkkana','Paprika'],['strawberry','Mansikka','Vadelma','Mustikka','Puolukka'],['fox','Kettu','Susi','Karhu','Ilves'],['owl','Pöllö','Varis','Kotka','Lokki'],['needle','Neula','Naru','Nappi','Sakset'],['umbrella','Sateenvarjo','Saapas','Sadetakki','Hattu'],['wallet','Lompakko','Laukku','Tasku','Kello'],['journey','Matka','Päiväkirja','Kysymys','Tapaaminen'],['carpenter','Puuseppä','Sähköasentaja','Putkimies','Leipuri'],['receipt','Kuitti','Resepti','Lippu','Velka']
]);
facts('bio','Luonto','Mikä vaihtoehto sopii parhaiten sanaan {x}?',[
 ['Kyy','Matelija','Nisäkäs','Lintu','Hyönteinen'],['Ahven','Kala','Matelija','Nisäkäs','Lintu'],['Mehiläinen','Hyönteinen','Hämähäkkieläin','Matelija','Nisäkäs'],['Hämähäkki','Hämähäkkieläin','Hyönteinen','Nisäkäs','Kala'],['Delfiini','Nisäkäs','Kala','Matelija','Lintu'],['Lepakko','Nisäkäs','Lintu','Hyönteinen','Kala'],['Strutsi','Lintu','Nisäkäs','Matelija','Hyönteinen'],['Pingviini','Lintu','Nisäkäs','Kala','Matelija'],['Kilpikonna','Matelija','Nisäkäs','Sammakkoeläin','Kala'],['Sammakko','Sammakkoeläin','Matelija','Kala','Hyönteinen'],['Mänty','Havupuu','Lehtipuu','Sieni','Heinä'],['Koivu','Lehtipuu','Havupuu','Sieni','Sammal'],['Kuusi','Havupuu','Lehtipuu','Sieni','Pensaskasvi'],['Herkkutatti','Sieni','Puu','Marja','Heinä'],['Valkovuokko','Kukkiva kasvi','Sieni','Sammal','Havupuu'],['Meritähti','Piikkinahkainen','Kala','Nisäkäs','Lintu'],['Mustekala','Nilviäinen','Kala','Nisäkäs','Matelija'],['Koralli','Eläin','Kasvi','Sieni','Kivilaji'],['Poron sarvet','Luuta','Karvaa','Keratiinia vain','Puuta'],['Valas','Nisäkäs','Kala','Matelija','Sammakkoeläin']
]);
facts('sport','Urheilu','Mihin lajiin termi {x} kuuluu?',[
 ['Paitsio','Jalkapallo ja jääkiekko','Tennis','Golf','Uinti'],['Birdie','Golf','Jääkiekko','Koripallo','Jalkapallo'],['Eagle','Golf','Tennis','Pesäpallo','Uinti'],['Ippon','Judo','Golf','Koripallo','Uinti'],['Slam dunk','Koripallo','Jääkiekko','Jalkapallo','Tennis'],['Syöttöruutu','Tennis','Jääkiekko','Golf','Uinti'],['Kunnari','Pesäpallo','Tennis','Golf','Uinti'],['Lukkari','Pesäpallo','Jääkiekko','Koripallo','Golf'],['Vapaauinti','Uinti','Jääkiekko','Tennis','Judo'],['Piruetti','Taitoluistelu','Golf','Jalkapallo','Pesäpallo'],['Rangaistuslaukaus','Jääkiekko','Golf','Tennis','Uinti'],['Keihäs','Yleisurheilu','Golf','Jalkapallo','Uinti'],['Ponnistuslauta','Pituushyppy','Jääkiekko','Golf','Tennis'],['Libero','Lentopallo','Golf','Uinti','Judo'],['Try eli yritys','Rugby','Golf','Jääkiekko','Tennis'],['Snatch eli tempaus','Painonnosto','Jalkapallo','Golf','Uinti'],['Slalom','Alppihiihto','Golf','Pesäpallo','Uinti'],['Frame','Snooker','Jalkapallo','Uinti','Golf'],['Checkmate','Shakki','Golf','Judo','Jalkapallo'],['Hat trick eli hattutemppu','Kolme maalia samalta pelaajalta','Kolme vaihtoa','Kolme kulmapotkua','Kolme erätaukoa']
]);
const capitals=[
 ['Suomi','Helsinki'],['Ruotsi','Tukholma'],['Norja','Oslo'],['Tanska','Kööpenhamina'],['Islanti','Reykjavík'],['Viro','Tallinna'],['Latvia','Riika'],['Liettua','Vilna'],['Puola','Varsova'],['Saksa','Berliini'],['Ranska','Pariisi'],['Espanja','Madrid'],['Portugali','Lissabon'],['Italia','Rooma'],['Kreikka','Ateena'],['Itävalta','Wien'],['Tšekki','Praha'],['Slovakia','Bratislava'],['Unkari','Budapest'],['Romania','Bukarest'],['Bulgaria','Sofia'],['Kroatia','Zagreb'],['Slovenia','Ljubljana'],['Serbia','Belgrad'],['Bosnia ja Hertsegovina','Sarajevo'],['Montenegro','Podgorica'],['Albania','Tirana'],['Pohjois-Makedonia','Skopje'],['Belgia','Bryssel'],['Luxemburg','Luxemburg'],['Irlanti','Dublin'],['Yhdistynyt kuningaskunta','Lontoo'],['Malta','Valletta'],['Kypros','Nikosia'],['Ukraina','Kiova'],['Valko-Venäjä','Minsk'],['Moldova','Chișinău'],['Venäjä','Moskova'],['Japani','Tokio'],['Etelä-Korea','Soul'],['Kiina','Peking'],['Mongolia','Ulan Bator'],['Thaimaa','Bangkok'],['Vietnam','Hanoi'],['Laos','Vientiane'],['Kambodža','Phnom Penh'],['Malesia','Kuala Lumpur'],['Singapore','Singapore'],['Filippiinit','Manila'],['Intia','New Delhi'],['Nepal','Kathmandu'],['Bangladesh','Dhaka'],['Pakistan','Islamabad'],['Bhutan','Thimphu'],['Turkki','Ankara'],['Georgia','Tbilisi'],['Armenia','Jerevan'],['Azerbaidžan','Baku'],['Jordania','Amman'],['Libanon','Beirut'],['Irak','Bagdad'],['Iran','Teheran'],['Saudi-Arabia','Riad'],['Qatar','Doha'],['Oman','Masqat'],['Egypti','Kairo'],['Marokko','Rabat'],['Tunisia','Tunis'],['Algeria','Alger'],['Kenia','Nairobi'],['Etiopia','Addis Abeba'],['Ghana','Accra'],['Nigeria','Abuja'],['Senegal','Dakar'],['Uganda','Kampala'],['Tansania','Dodoma'],['Ruanda','Kigali'],['Sambia','Lusaka'],['Zimbabwe','Harare'],['Namibia','Windhoek'],['Botswana','Gaborone'],['Lesotho','Maseru'],['Madagaskar','Antananarivo'],['Kanada','Ottawa'],['Yhdysvallat','Washington, D.C.'],['Meksiko','México'],['Kuuba','Havanna'],['Jamaika','Kingston'],['Brasilia','Brasília'],['Argentiina','Buenos Aires'],['Chile','Santiago'],['Peru','Lima'],['Kolumbia','Bogotá'],['Ecuador','Quito'],['Uruguay','Montevideo'],['Paraguay','Asunción'],['Australia','Canberra'],['Uusi-Seelanti','Wellington'],['Fidži','Suva'],['Papua-Uusi-Guinea','Port Moresby']
];
capitals.forEach(([country,capital],i)=>{
  const offsets=[7,23,41];const wrong=offsets.map(n=>capitals[(i+n)%capitals.length][1]);
  extraWorld.push(q(`cap${i}`,`Mikä on maan ${country} pääkaupunki?`,[capital,...wrong],0,`${country}: pääkaupunki on ${capital}.`,'globe','Maantieto',`capital-${i}`));
  extraGeneral.push(q(`city${i}`,`Missä maassa ${capital} sijaitsee?`,[country,...offsets.map(n=>capitals[(i+n)%capitals.length][0])],0,`${capital} sijaitsee maassa ${country}.`,null,'Maantieto',`capital-${i}`));
});
// Laskutehtävät generoidaan täsmällisesti; vaihtoehdot eivät voi olla päällekkäisiä.
for(let i=0;i<180;i++){
  const a=3+i%17,b=2+Math.floor(i/17)%11,kind=i%6;let prompt,result,explanation;
  if(kind===0){result=a*b;prompt=`Pöydässä on ${a} pelaajaa. Jokainen saa ${b} pelimerkkiä. Montako merkkiä tarvitaan?`;explanation=`${a} × ${b} = ${result}.`;}
  if(kind===1){result=a+b;prompt=`Pankissa on ${a} pistettä ja saat ${b} lisää. Mikä on uusi saldo?`;explanation=`${a} + ${b} = ${result}.`;}
  if(kind===2){result=a;prompt=`${a*b} karkkia jaetaan tasan ${b} ihmiselle. Montako jokainen saa?`;explanation=`${a*b} ÷ ${b} = ${a}.`;}
  if(kind===3){result=2*(a+b);prompt=`Suorakulmion sivut ovat ${a} ja ${b} metriä. Mikä on sen piiri?`;explanation=`2 × (${a} + ${b}) = ${result} metriä.`;}
  if(kind===4){result=a*10;prompt=`Mikä on ${a*5} prosenttia luvusta 200?`;explanation=`${a*5} % × 200 = ${result}.`;}
  if(kind===5){result=a+b*2;prompt=`Mikä on ${a} + ${b} × 2, kun käytetään tavallista laskujärjestystä?`;explanation=`Ensin kertolasku: ${b} × 2 = ${b*2}. Sitten ${a} + ${b*2} = ${result}.`;}
  extraGeneral.push(q(`math${i}`,prompt,[String(result),String(result+1),String(result+3),String(Math.max(0,result-2))],0,explanation,null,'Logiikka'));
}
const addOrder=(id,prompt,items,explanation)=>extraOrder.push({id,prompt,items,explanation,category:id.startsWith('months')?'Kuukaudet':id.startsWith('numbers')?'Luvut':'Yleistieto',family:'order:'+items.join('|')});
const months=['Tammikuu','Helmikuu','Maaliskuu','Huhtikuu','Toukokuu','Kesäkuu','Heinäkuu','Elokuu','Syyskuu','Lokakuu','Marraskuu','Joulukuu'];
for(let i=0;i<28;i++){const set=[i%3,3+i%3,6+Math.floor(i/3)%3,9+Math.floor(i/9)%3];const items=set.map(n=>months[n]);addOrder(`months${i}`,'Järjestä nämä kuukaudet kalenterijärjestykseen.',items,items.join(' → '));}
for(let i=0;i<32;i++){const start=i-16,items=[start,start+2+i%3,start+8,start+12].map(String);addOrder(`numbers${i}`,'Järjestä luvut pienimmästä suurimpaan.',items,items.join(' < '));}
[
 ['Laita ihmisen elämänvaiheet aikajärjestykseen.',['Vauva','Lapsi','Nuori','Aikuinen']],['Järjestä nämä yksiköt pienimmästä suurimpaan.',['Gramma','Kilogramma','Tonni','Kilotonnia']],['Järjestä merkit arvojärjestykseen pienimmästä suurimpaan.',['I','V','X','L']],['Järjestä lämpötilat kylmimmästä kuumimpaan.',['−20 °C','0 °C','20 °C','100 °C']],['Järjestä kielisoittimet tyypillisestä korkeimmasta matalimpaan.',['Viulu','Alttoviulu','Sello','Kontrabasso']],['Järjestä luvut pienimmästä suurimpaan.',['¼','½','¾','1']],['Järjestä Suomen tapahtumat aikajärjestykseen.',['Itsenäistyminen','Talvisodan alku','Helsingin olympialaiset','Ensimmäinen jääkiekon MM-kulta']],['Järjestä tapahtumat aikajärjestykseen.',['Kirjoitustaidon synty','Kirjapainotaidon leviäminen Euroopassa','Ensimmäinen moottorilento','Ensimmäinen kuukävely']],['Järjestä veden lämpötilat kylmimmästä kuumimpaan.',['−10 °C','0 °C','50 °C','100 °C']],['Järjestä aakkosjärjestykseen.',['Aalto','Koivu','Mänty','Puro']],['Järjestä aakkosjärjestykseen.',['Ankka','Kettu','Leijona','Susi']],['Järjestä aakkosjärjestykseen.',['Helsinki','Oulu','Tampere','Turku']],['Järjestä viikonpäivät.',['Tiistai','Torstai','Lauantai','Sunnuntai']],['Järjestä etäisyydet lyhyimmästä pisimpään.',['100 metriä','500 metriä','2 kilometriä','10 kilometriä']],['Järjestä euroarvot pienimmästä suurimpaan.',['50 senttiä','1 euro','2 euroa','5 euroa']],['Järjestä kellonajat vuorokauden alusta lukien.',['00.30','06.00','12.00','23.45']],['Järjestä suuruusjärjestykseen pienimmästä suurimpaan.',['Kylä','Kaupunki','Valtio','Maanosa']],['Järjestä laskutoimitusten tulokset pienimmästä suurimpaan.',['1 + 1','2 × 2','3 × 3','4 × 4']],['Järjestä juoksukilpailun sijoitukset parhaasta heikoimpaan.',['Kulta','Hopea','Pronssi','Neljäs sija']],['Järjestä ajanjaksot lyhyimmästä pisimpään.',['Viikko','Kuukausi','Vuosi','Vuosikymmen']]
].forEach(([prompt,items],i)=>addOrder(`curatedorder${i}`,prompt,items,items.join(' → ')));
for(let h=1;h<=12;h++)for(const minute of [5,15,25,40]){
  const label=`${h}.${String(minute).padStart(2,'0')}`;const alternatives=[`${h}.${String((minute+30)%60).padStart(2,'0')}`,`${h%12+1}.${String(minute).padStart(2,'0')}`,`${(h+5)%12+1}.${String(minute).padStart(2,'0')}`];
  extraImages.push(q(`clock${h}-${minute}`,'Mitä kellonaikaa analoginen kello näyttää?',[label,...alternatives],0,`Kello näyttää ${label}.`,{kind:'clock',hour:h,minute},'Kuvapähkinät'));
}
for(let n=2;n<=7;n++){const count=n*(n+1)*(2*n+1)/6;extraImages.push(q(`grid${n}`,`Kuinka monta erikokoista neliötä kuvassa on?`,[String(count),String(n*n),String(count+2),String(count+5)],0,`Lasketaan jokaisen koon neliöt: ${Array.from({length:n},(_,i)=>(i+1)**2).join(' + ')} = ${count}.`,{kind:'squares',n},'Kuvapähkinät'));}
for(let n=1;n<=6;n++)extraImages.push(q(`die${n}`,'Tavallisen nopan vastakkaisten sivujen summa on 7. Mikä on kuvassa näkyvän sivun vastapuolella?',[String(7-n),String(n===3?2:n),String(n+7),String(n+10)],0,`7 − ${n} = ${7-n}.`,{kind:'dice',n},'Kuvapähkinät'));
for(let i=0;i<30;i++){const a=2+i,b=2+i%4,value=a*b*b*b;extraImages.push(q(`seq${i}`,'Mikä luku jatkaa kuvan sarjaa?',[String(value),String(value+b),String(value+1),String(value-b)],0,`Jokainen luku kerrotaan luvulla ${b}.`,{kind:'sequence',values:[a,a*b,a*b*b]},'Kuvapähkinät'));}
for(let i=0;i<12;i++){const n=4+i,marked=2+i%5;extraImages.push(q(`dots${i}`,'Kuinka monta violettia ympyrää kuvassa on?',[String(marked),String(marked+1),String(marked+2),String(marked+3)],0,`Violetteja ympyröitä on ${marked}. Muut ovat turkooseja.`,{kind:'dots',n,marked},'Kuvapähkinät'));}

for(const q of extraImages)q.category=({clock:'Kellot',squares:'Ruudukot',dice:'Nopat',sequence:'Sarjat',dots:'Havainnointi'})[q.art.kind];
